### ISSUE TITLE
Fix pagination for Chrome 22+ when zooming

### ISSUE THREAD

**Issue by nono** [TEA-ebook/teabook-open-reader#1]
Hi,

as you know, when using Chrome 22+ and zooming, the pages can be cut on left or right. I've tried to fix this issue but I'm really unsure about my code. So, I've opened a pull-request on Monocle to discuss it: https://github.com/joseph/Monocle/pull/146

**Comment by eunomie** [comment]
I've rewrite it to reduce the calls to the DOM : https://github.com/joseph/Monocle/pull/161
