### ISSUE TITLE
Find a new way to navigate through the pages

### ISSUE THREAD

**Issue by eunomie** [TEA-ebook/teabook-open-reader#18]
To navigate through the pages, it's possible to click the < and > icons and the left and right of pages.
The size of the area to click is variable, set to `10%` of page width (`body #reader .monelem_panel` css selector to find them).

The problem is the area is on top of some text and if the text contains links (like footnode) the links are not clickable.
It's necessary to find a way to click the left/right area of pages to go back / forward but let the links in the text clickable.

**Comment by astranchet** [comment]
Something à la I-Mode Panel could be a solution : http://test.monoclejs.com/test/panels/index.html
