### ISSUE TITLE
Can't find a way to logout

### ISSUE THREAD

**Issue by brunobord** [TEA-ebook/teabook-open-reader#2]
Hi,

On the demo site : when I pick a demo account (e.g. the "demo-liseuse1"), I do access to the library. But after that, it's impossible to log out and try to pick another one.

The only way I've found was to delete the browser cookies linked to the demo website.
Wouldn't it be nice to have a logout button?

**Comment by eunomie** [comment]
Hi,

A logout link has been added on the demo site.
This is just a quick and dirty link, but you can disconnect without manually delete cookies

Yves
